### ISSUE TITLE
Readme update on python3-bcc dependency

### ISSUE THREAD

**Issue by SPYFF** [m-sch/tracerface#31]
As of today in major distros like Ubuntu I cant find the package `python3-bcc`. The package however available in iovisor's repo, detailed here: https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary

I think it would be helpful to highlight that somewhere. Or if normal apt install method on the package works I would be grateful to know on which distro (on Ubuntu 19.10 the package not available or it has different name)

**Comment by m-sch** [comment]
You are right, the requirements are missing to be able to install the package. Unfortunately they don't mention this package explicitly in the bcc install guide, but I will link it in the readme and add a short explanation about how to get it.
Also I don't think this package is found in the package index of any ubuntu versions by default unfortunately...

**Comment by m-sch** [comment]
It turns out there is the `python3-bpfcc` package which can installed normally however it is outdated and it doesn't work with the app.
